#! /bin/bash

sudo touch /etc/apt/sources.list.d/mint.list

echo "deb http://packages.linuxmint.com vera main upstream import backport" | sudo tee -a /etc/apt/sources.list.d/mint.list
echo "deb-src http://packages.linuxmint.com vera main upstream import backport" | sudo tee -a /etc/apt/sources.list.d/mint.list

sudo apt update
