#! /bin/bash

sudo touch /etc/apt/sources.list.d/mint.list

echo "deb http://packages.linuxmint.com vera main upstream import backport" | sudo tee -a /etc/apt/sources.list.d/mint.list
echo "deb-src http://packages.linuxmint.com vera main upstream import backport" | sudo tee -a /etc/apt/sources.list.d/mint.list

wget http://packages.linuxmint.com/pool/main/l/linuxmint-keyring/linuxmint-keyring_2022.06.21_all.deb -P /home/$USER/Downloads

sudo dpkg -i /home/$USER/Downloads/linuxmint-keyring_2022.06.21_all.deb

sudo apt update
